version: "3.3"
services:
  jaeger:
    image: "jaegertracing/all-in-one:1.18"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

#  zipkin_mysql:
#    image: openzipkin/zipkin-mysql
#    container_name: openzipkin_zipkin_mysql
#
#  zipkin:
#    image: "openzipkin/zipkin"
#    container_name: openzipkin_zipkin
#    ports:
#      - "9411:9411"
#    environment:
#      - STORAGE_TYPE=mysql
#      # Point the zipkin at the storage backend
#      - MYSQL_HOST=zipkin_mysql
#      # Uncomment to enable scribe
#      # - SCRIBE_ENABLED=true
#      # Uncomment to enable self-tracing
#      # - SELF_TRACING_ENABLED=true
#      # Uncomment to enable debug logging
#      # - JAVA_OPTS=-Dlogging.level.zipkin2=DEBUG
#    depends_on:
#      - zipkin_mysql
